name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    name: release ${{ matrix.goos }}/${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: darwin
            goarch: arm64
          - goos: linux
            goarch: amd64
    steps:
      - uses: actions/checkout@v4

      - uses: wangyoucao577/go-release-action@v1
        env:
          CGO_ENABLED: "0"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: go.mod
          binary_name: agentmark
          sha256sum: "TRUE"
          md5sum: "FALSE"
